### ISSUE TITLE
New build button disappeared. MacOS 15 related?

### ISSUE THREAD

**Issue by oronbz** [sergeykhliustin/buildio#22]
I've noticed I can no longer start manual builds through the app. Is it a known issue?
![image](https://github.com/user-attachments/assets/8d330415-4f01-4379-ba42-035895da2ddd)

**Comment by oronbz** [comment]
Any chance this could be looked at @sergeykhliustin ?

**Comment by sergiikhliustin** [comment]
@oronbz fixed in 2.0.0
